# Generated by Django 4.2.27 on 2025-12-15 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moment",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="moments",
                through="moments.MomentTag",
                to="moments.tag",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="moment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="moments.moment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="momenttag",
            unique_together={("moment", "tag")},
        ),
    ]
