# Generated by Django 4.2.27 on 2025-12-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interactions", "0001_initial"),
        ("moments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="moment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="moments.moment",
            ),
        ),
    ]
